[technote]
id = "SITCOMTN-082"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-082.lsst.io/"
github_url = "https://github.com/lsst-sitcom/sitcomtn-082"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"
[[technote.authors]]
name = {given = "Yijung", family = "Kang"}
internal_id = "kangy"
orcid = "https://orcid.org/0000-0002-5261-5803"
[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC-Kavli"
ror = "https://ror.org/00pwqz914"

[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory"
internal_id = "RubinObsC"
ror = "https://ror.org/048g3cy84"

[[technote.authors]]
name = {given = "Bruno C.", family = "Quint"}
internal_id = "quintb"
orcid = "https://orcid.org/0000-0002-1557-3560"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
ror = "https://ror.org/048g3cy84"
